accepted = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "OpenSSL",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "Zlib",
]
ignore-dev-dependencies = true
private.ignore = true
targets = [
    "aarch64-unknown-linux-musl",
    "armv7-unknown-linux-musleabihf",
    "i686-unknown-linux-musl",
    "riscv64gc-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
]
workarounds = ["ring"]
