[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
ahash = "0.8.11"
anyhow = "1.0.86"
ar = "0.9.0"
base64-simd = "0.8.0"
bitflags = "2.6.0"
bstr = "1.9.1"
bzip2 = "0.4.4"
cached = { version = "0.53.1", default-features = false }
camino = "1.1.7"
cfg-if = "1.0.0"
clap = "4.5.11"
clap_complete = "4.5.11"
clap_mangen = "0.2.23"
clru = "0.6.2"
compact_str = "0.8.0"
console = "0.15.8"
dashmap = "6.0.1"
derive_builder = "0.20.0"
directories = "5.0.1"
dirs = "5.0.1"
duct = "0.13.7"
either = "1.13.0"
env_logger = "0.11.5"
faster-hex = { version = "0.9.0", default-features = false }
flate2 = { version = "1.0.30", default-features = false, features = [
    "zlib-ng",
] }
flume = { version = "0.11.0", default-features = false }
glob = "0.3.1"
ignore = "0.4.22"
indoc = "2.0.5"
itertools = "0.13.0"
lasso = "0.7.2"
libc = "0.2.155"
log = "0.4.22"
md-5 = "0.10.6"
memchr = "2.7.4"
mimalloc = "0.1.43"
nix = { version = "0.29.0", default-features = false }
num_cpus = "1.16.0"
os_info = { version = "3.8.2", default-features = false }
ouroboros = "0.18.4"
parking_lot = "0.12.3"
phf = "0.11.2"
pretty_assertions = "1.4.0"
proc-exit = "2.0.2"
rayon = "1.10.0"
regex = "1.10.5"
ring = "0.17.8"
rune = "0.13.4"
rune-modules = "0.13.4"
rust-ini = "0.21.0"
scopeguard = "1.2.0"
serde = "1.0.204"
serde_json = "1.0.120"
smallvec = { version = "1.13.2", features = [
    "const_generics",
    "const_new",
    "union",
] }
strum = { version = "0.26.3", features = ["derive"] }
sysinfo = "0.30.13"
tar = "0.4.41"
tempfile = "3.10.1"
thiserror = "1.0.63"
tokio = "1.39.1"
tracing = "0.1.40"
tracing-log = "0.2.0"
tracing-subscriber = "0.3.18"
winnow = "0.6.16"
xz2 = "0.1.7"
zstd = "0.13.2"

[workspace.lints.rust]
rust-2018-idioms = "warn"

[workspace.lints.clippy]
doc_markdown = "warn"
needless_pass_by_value = "warn"
redundant_closure_for_method_calls = "warn"
semicolon_if_nothing_returned = "warn"
undocumented_unsafe_blocks = "warn"
unnecessary_safety_doc = "warn"
unwrap_used = "warn"
wildcard_imports = "warn"

[profile.dev]
debug = 2
split-debuginfo = "unpacked"

[profile.release]
lto = "thin"
opt-level = 2

[profile.profiling]
debug = 2
inherits = "release"
lto = false

[profile.dev.package]
# Needed for reasonable performance
flate2.opt-level = 2
libz-ng-sys.opt-level = 2
md-5.opt-level = 2
proc-macro2.opt-level = 2
quote.opt-level = 2
ring.opt-level = 2
rune-macros.opt-level = 2
serde_derive.opt-level = 2
syn.opt-level = 2
zstd-safe.opt-level = 2
zstd-sys.opt-level = 2
zstd.opt-level = 2

#[patch.crates-io]
## Rune
#rune = { path = "patches/rune/crates/rune" }
