[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
ahash = "0.8.11"
anyhow = "1.0.81"
bitflags = "2.4.2"
bstr = "1.9.1"
clap = "4.5.3"
clap_complete = "4.5.1"
clap_mangen = "0.2.20"
compact_str = "0.7.1"
dashmap = "5.5.3"
derive_builder = "0.20.0"
either = "1.10.0"
env_logger = "0.11.3"
faster-hex = { version = "0.9.0", default-features = false }
flate2 = "1.0.28"
flume = { version = "0.11.0", default-features = false }
ignore = "0.4.22"
indoc = "2.0.4"
lasso = "0.7.2"
log = "0.4.21"
md-5 = "0.10.6"
memchr = "2.7.1"
num_cpus = "1.16.0"
os_info = { version = "3.8.1", default-features = false }
phf = "0.11.2"
pretty_assertions = "1.4.0"
proc-exit = "2.0.1"
rayon = "1.9.0"
regex = "1.10.3"
ring = "0.17.8"
rust-ini = "0.21.0"
smallvec = "1.13.1"
strum = "0.26.2"

[profile.dev]
debug = 2
split-debuginfo = "unpacked"

[profile.release]
lto = "fat"
opt-level = 2

[profile.profiling]
debug = 2
inherits = "release"

[profile.dev.package.ring]
opt-level = 2

[profile.dev.package.md-5]
opt-level = 2
