[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
ahash = "0.8.11"
anyhow = "1.0.86"
ar = "0.9.0"
base64-simd = "0.8.0"
bitflags = "2.6.0"
bstr = "1.9.1"
bzip2 = "0.4.4"
camino = "1.1.7"
cfg-if = "1.0.0"
clap = "4.5.9"
clap_complete = "4.5.8"
clap_mangen = "0.2.22"
compact_str = "0.7.1"
dashmap = "6.0.1"
derive_builder = "0.20.0"
dirs = "5.0.1"
either = "1.13.0"
env_logger = "0.11.3"
faster-hex = { version = "0.9.0", default-features = false }
flate2 = { version = "1.0.30", default-features = false, features = [
    "zlib-ng",
] }
flume = { version = "0.11.0", default-features = false }
glob = "0.3.1"
ignore = "0.4.22"
indoc = "2.0.5"
lasso = "0.7.2"
libc = "0.2.155"
log = "0.4.22"
md-5 = "0.10.6"
memchr = "2.7.4"
mimalloc = "0.1.43"
nix = { version = "0.29.0", default-features = false }
num_cpus = "1.16.0"
os_info = { version = "3.8.2", default-features = false }
phf = "0.11.2"
pretty_assertions = "1.4.0"
proc-exit = "2.0.1"
rayon = "1.10.0"
regex = "1.10.5"
ring = "0.17.8"
rust-ini = "0.21.0"
scopeguard = "1.2.0"
serde = "1.0.204"
serde_json = "1.0.120"
smallvec = "1.13.2"
strum = "0.26.3"
tar = "0.4.41"
thiserror = "1.0.63"
winnow = "0.6.14"
xz2 = "0.1.7"
zstd = "0.13.2"

[workspace.lints.rust]
rust-2018-idioms = "warn"

[workspace.lints.clippy]
doc_markdown = "warn"
needless_pass_by_value = "warn"
redundant_closure_for_method_calls = "warn"
semicolon_if_nothing_returned = "warn"
unwrap_used = "warn"
wildcard_imports = "warn"

[profile.dev]
debug = 2
split-debuginfo = "unpacked"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 2

[profile.profiling]
debug = 2
inherits = "release"

[profile.dev.package.ring]
opt-level = 2

[profile.dev.package.md-5]
opt-level = 2
