[package]
categories = ["filesystem", "os::linux-apis"]
description = "Check installed distro files for changes (caching library)"
edition = "2021"
keywords = ["package-management"]
license = "MPL-2.0"
name = "paketkoll_cache"
repository = "https://github.com/VorpalBlade/paketkoll"
rust-version = "1.79.0"
version = "0.2.0"

[dependencies]
ahash.workspace = true
anyhow.workspace = true
cached = { workspace = true, features = [
    "disk_store",
    "ahash",
], default-features = false }
compact_str.workspace = true
dashmap.workspace = true
paketkoll_types = { version = "0.1.1", path = "../paketkoll_types", features = [
    "serde",
] }
rayon.workspace = true
serde = { workspace = true, features = ["derive"] }
tracing.workspace = true

[lints]
workspace = true
