[package]
categories = ["filesystem", "os::linux-apis"]
description = "Check installed distro files for changes (core library)"
edition = "2021"
keywords = ["apt", "arch-linux", "debian", "pacman", "package-management"]
license = "MPL-2.0"
name = "paketkoll_core"
repository = "https://github.com/VorpalBlade/paketkoll"
rust-version = "1.76.0"
version = "0.3.1"

    [package.metadata.docs.rs]
    default-target = "x86_64-unknown-linux-gnu"
    features = ["arch_linux", "debian"]
    # Other targets make no difference, and we only support Linux
    targets = []

[features]
# Default features
default = []

# Include the Arch Linux backend
arch_linux = [
    #"dep:mtree",
    "__sha256",
    "dep:flate2",
    "dep:rust-ini",
    "dep:dashmap",
]

# Include support for the Debian backend
debian = ["__md5", "dep:dashmap", "dashmap/rayon"]

# Include support for serde on public datatypes
serde = ["dep:serde", "bitflags/serde", "smallvec/serde", "compact_str/serde"]

# Internal feature: Enable MD5 support
__md5 = ["dep:md-5"]
# Internal feature: Enable SHA-256 support
__sha256 = ["dep:ring"]

[dependencies]
ahash = { workspace = true }
anyhow = { workspace = true, features = ["backtrace"] }
bitflags = { workspace = true }
bstr = { workspace = true }
cfg-if = { workspace = true }
compact_str = { workspace = true, features = ["smallvec"] }
dashmap = { workspace = true, optional = true }
derive_builder = { workspace = true }
either = { workspace = true }
faster-hex = { workspace = true, features = ["std"] }
flate2 = { workspace = true, optional = true }
flume = { workspace = true }
ignore = { workspace = true, features = ["simd-accel"] }
lasso = { workspace = true, features = [
    "ahasher",
    "inline-more",
    "multi-threaded",
] }
log = { workspace = true }
md-5 = { workspace = true, optional = true }
memchr = { workspace = true }
num_cpus = { workspace = true }
#mtree = { version = "0.5.0", optional = true }
phf = { workspace = true, features = ["macros"] }
rayon = { workspace = true }
regex = { workspace = true }
ring = { workspace = true, optional = true }
rust-ini = { workspace = true, optional = true }
scopeguard = { workspace = true }
serde = { workspace = true, optional = true, features = ["derive"] }
smallvec = { workspace = true, features = [
    "const_generics",
    "const_new",
    "union",
] }
strum = { workspace = true, features = ["derive"] }

[dev-dependencies]
indoc = { workspace = true }
pretty_assertions = { workspace = true }

[lints]
workspace = true
