[package]
categories = ["filesystem", "os::linux-apis"]
description = "Check installed distro files for changes (core library)"
edition = "2021"
keywords = ["apt", "arch-linux", "debian", "pacman", "package-management"]
license = "MPL-2.0"
name = "paketkoll_core"
repository = "https://github.com/VorpalBlade/paketkoll"
rust-version = "1.76.0"
version = "0.3.0"

    [package.metadata.docs.rs]
    default-target = "x86_64-unknown-linux-gnu"
    features = ["arch_linux", "debian"]
    # Other targets make no difference, and we only support Linux
    targets = []

[features]
# Default features
default = []

# Include the Arch Linux backend
arch_linux = [
    #"dep:mtree",
    "__sha256",
    "dep:flate2",
    "dep:rust-ini",
    "dep:dashmap",
]

# Include support for the Debian backend
debian = ["__md5", "dep:dashmap", "dashmap/rayon"]

# Internal feature: Enable MD5 support
__md5 = ["dep:md-5"]
# Internal feature: Enable SHA-256 support
__sha256 = ["dep:ring"]

[dependencies]
ahash = "0.8.11"
anyhow = { version = "1.0.80", features = ["backtrace"] }
bitflags = "2.4.2"
bstr = "1.9.1"
compact_str = { version = "0.7.1", features = ["smallvec"] }
dashmap = { version = "5.5.3", optional = true }
derive_builder = "0.20.0"
either = "1.10.0"
faster-hex = { version = "0.9.0", default-features = false, features = ["std"] }
flate2 = { version = "1.0.28", features = ["zlib-ng"], optional = true }
flume = { version = "0.11.0", default-features = false }
ignore = { version = "0.4.22", features = ["simd-accel"] }
lasso = { version = "0.7.2", features = [
    "ahasher",
    "inline-more",
    "multi-threaded",
] }
log = "0.4.21"
md-5 = { version = "0.10.6", optional = true }
num_cpus = "1.16.0"
#mtree = { version = "0.5.0", optional = true }
phf = { version = "0.11.2", features = ["macros"] }
rayon = "1.9.0"
regex = "1.10.3"
ring = { version = "0.17.8", optional = true }
rust-ini = { version = "0.20.0", optional = true }
smallvec = { version = "1.13.1", features = [
    "const_generics",
    "const_new",
    "union",
] }
strum = { version = "0.26.2", features = ["derive"] }

[dev-dependencies]
indoc = "2.0.4"
pretty_assertions = "1.4.0"
