[package]
description = "Scripting language for Konfigkoll (not for direct public use)"
edition = "2021"
license = "MPL-2.0"
name = "konfigkoll_script"
repository = "https://github.com/VorpalBlade/paketkoll"
rust-version = "1.79.0"
version = "0.1.0"

[features]
# Default features
default = []

# Include the Arch Linux backend
arch_linux = ["paketkoll_core/arch_linux"]

# Include support for the Debian backend
debian = ["paketkoll_core/debian"]

[dependencies]
ahash.workspace = true
anyhow.workspace = true
camino.workspace = true
compact_str.workspace = true
glob.workspace = true
itertools.workspace = true
konfigkoll_hwinfo = { version = "0.1.0", path = "../konfigkoll_hwinfo", features = [
    "rune",
] }
konfigkoll_types = { version = "0.1.0", path = "../konfigkoll_types" }
konfigkoll_utils = { version = "0.1.0", path = "../konfigkoll_utils" }
nix = { workspace = true, features = ["user"] }
paketkoll_core = { version = "0.5.0", path = "../paketkoll_core" }
paketkoll_types = { version = "0.1.0", path = "../paketkoll_types", features = [
    "serde",
] }
paketkoll_utils = { version = "0.1.0", path = "../paketkoll_utils" }
parking_lot.workspace = true
regex.workspace = true
rune-modules = { workspace = true, features = [
    "process",
    "json",
    "toml",
    "tokio",
] }
rune.workspace = true
rust-ini.workspace = true
smallvec.workspace = true
sysinfo.workspace = true
tempfile = { workspace = true }
thiserror.workspace = true
tokio = { workspace = true, features = ["process"] }
tracing.workspace = true
winnow = { workspace = true, features = ["simd"] }

[lints]
workspace = true

[dev-dependencies]
indoc.workspace = true
pretty_assertions.workspace = true
