[package]
categories = [
    "command-line-utilities",
    "config",
    "filesystem",
    "os::linux-apis",
]
description = "Konfigkoll is a configuration management tool for Arch Linux and Debian (and derivatives)"
edition = "2024"
keywords = ["apt", "arch-linux", "config-management", "debian", "pacman"]
license = "MPL-2.0"
name = "konfigkoll"
repository = "https://github.com/VorpalBlade/paketkoll"
rust-version = "1.88.0"
version = "0.1.16"

[[bin]]
name = "konfigkoll"
path = "src/main.rs"

[[bin]]
name = "konfigkoll-rune"
path = "src/bin/rune.rs"

[features]
# Default features
default = ["arch_linux", "debian", "vendored"]

# Include the Arch Linux backend
arch_linux = ["paketkoll_core/arch_linux"]

# Include support for the Debian backend
debian = ["paketkoll_core/debian"]

# Vendor C/C++ dependencies instead of linking them dynamically
vendored = ["paketkoll_core/vendored"]

[dependencies]
ahash.workspace = true
camino.workspace = true
clap.workspace = true
color-eyre.workspace = true
compact_str.workspace = true
dashmap.workspace = true
directories.workspace = true
either.workspace = true
eyre.workspace = true
itertools.workspace = true
konfigkoll_core = { version = "0.5.7", path = "../konfigkoll_core" }
konfigkoll_script = { version = "0.1.14", path = "../konfigkoll_script" }
konfigkoll_types = { version = "0.2.10", path = "../konfigkoll_types" }
konfigkoll_utils = { version = "0.1.10", path = "../konfigkoll_utils" }
ouroboros.workspace = true
paketkoll_cache = { version = "0.2.13", path = "../paketkoll_cache" }
paketkoll_core = { version = "0.5.14", path = "../paketkoll_core" }
paketkoll_types = { version = "0.3.0", path = "../paketkoll_types" }
paketkoll_workspace_hack = { version = "0.1", path = "../paketkoll_workspace_hack" }
rayon.workspace = true
rune = { workspace = true, features = ["cli"] }
tokio.workspace = true
tracing.workspace = true
tracing-error.workspace = true
tracing-subscriber.workspace = true

[target.'cfg(target_env = "musl")'.dependencies]
# The allocator on musl is attrociously slow, so we use a custom one.
# Jemalloc doesn't work reliably on Aarch64 due to varying page size, so use
# the slightly slower mimalloc instead.
mimalloc.workspace = true

[lints]
workspace = true
