[package]
description = "Type definitions for konfigkoll backend (internal helper crate)"
edition = "2021"
license = "MPL-2.0"
name = "konfigkoll_types"
repository = "https://github.com/VorpalBlade/paketkoll"
rust-version = "1.79.0"
version = "0.1.0"

[dependencies]
ahash.workspace = true
anyhow.workspace = true
bitflags.workspace = true
camino.workspace = true
compact_str.workspace = true
either.workspace = true
paketkoll_types = { version = "0.1.0", path = "../paketkoll_types" }
paketkoll_utils = { version = "0.1.0", path = "../paketkoll_utils" }
strum.workspace = true

[lints]
workspace = true
