name: Build (helper)

permissions:
  contents: read

on:
  workflow_call:

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_DEV_DEBUG: 0
  CARGO_TERM_COLOR: always
  PAKETKOLL_BUILDER: github-ci
  RUST_BACKTRACE: 1
  CC: clang
  RUSTFLAGS: "-D warnings"
  RUSTUP_MAX_RETRIES: 10

jobs:
  modern-default:
    # Test modern compilers on standard platforms on Linux.
    name: "${{ matrix.target }} - ${{ matrix.rust }} (default configuration)"
    runs-on: ubuntu-latest
    env:
      CARGO_PROFILE_DEV_DEBUG: 1
      CARGO_PROFILE_DEV_SPLIT_DEBUGINFO: ${{ matrix.debug_info }}
      RUSTFLAGS: -D warnings -Clink-arg=-Wl,--compress-debug-sections=zlib
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - i686-unknown-linux-musl
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
        rust:
          - stable
          - nightly
        debug_info:
          - packed
        include:
          # RISCV doesn't work with split debug info (see rust-lang/rust#110224)
          - target: riscv64gc-unknown-linux-gnu
            rust: stable
            debug_info: off
          - target: riscv64gc-unknown-linux-gnu
            rust: nightly
            debug_info: off
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Install Rust
        run: rustup install --profile minimal ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
      - name: Print environment info
        run: |
          echo "# Rust"
          rustc -Vv
          echo "# Cargo"
          cargo -Vv
          echo "# GCC"
          gcc -v
          echo "# Clang"
          clang -v
          echo "# Ld"
          ld -v
      - name: Install cross
        uses: taiki-e/install-action@14083e64ac8cf1f5e54356df00b9779b23e192a1 # v2.58.29
        with:
          tool: cross@latest
      # Cache doesn't work when cross compiling anyway.
      #- name: Cache builds
      #  uses: Swatinem/rust-cache@v2.7.8
      #  with:
      #    key: ${{ matrix.target }}-${{ matrix.rust }}
      - name: Cross compile binary
        run: cross build --locked --target ${{ matrix.target }} --verbose
      - name: Cross compile tests
        run: cross test --no-run --locked --target ${{ matrix.target }} --verbose
      - name: Cross test
        run: cross test --locked --target ${{ matrix.target }} --verbose
      - name: Compress binary
        if: matrix.rust == 'stable' && contains(matrix.target, 'musl')
        run: |
          mkdir paketkoll
          cp target/${{ matrix.target }}/debug/paketkoll paketkoll/
          cp target/${{ matrix.target }}/debug/konfigkoll paketkoll/
          if [[ -f target/${{ matrix.target }}/debug/paketkoll.dwp ]]; then
            # No split debug info for RISCV
            cp target/${{ matrix.target }}/debug/paketkoll.dwp paketkoll/
          fi
          if [[ -f target/${{ matrix.target }}/debug/konfigkoll.dwp ]]; then
            # No split debug info for RISCV
            cp target/${{ matrix.target }}/debug/konfigkoll.dwp paketkoll/
          fi
          tar cf paketkoll.tar paketkoll
          zstd -T0 -6 paketkoll.tar
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: matrix.rust == 'stable' && contains(matrix.target, 'musl')
        with:
          name: paketkoll_${{ matrix.target }}.tar.zst
          path: paketkoll.tar.zst
          retention-days: 7
      - name: Clean up temporary items
        run: |
          rm -rf paketkoll paketkoll.tar paketkoll.tar.zst

  configurations:
    # Test non-standard configurations, MSRV and Rust versions
    name: "Test: \"${{ matrix.features }}\" (Linux), Rust ${{ matrix.rust }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features:
          - --no-default-features --features=arch_linux
          - --no-default-features --features=debian
          - --all-features
        rust:
          - 1.88.0
          - stable
        include:
          # MSRV with default features too
          - features:
            rust: 1.88.0
          # Nightly will all features
          - features: --all-features
            rust: nightly
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Install Rust
        run: rustup install --profile minimal  ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
      - name: Get cargo-binstall
        run: |
          curl -L https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz | tar -zxf - && mv cargo-binstall $HOME/.cargo/bin/
      - name: Install required cargo addons
        run: cargo binstall --no-confirm --no-symlinks cargo-hakari
      - name: Disable cargo workspace hack (to properly test features)
        run: cargo hakari disable
      - name: Cache builds
        uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
      - name: Compile
        run: cargo test --locked ${{ matrix.features }} --verbose --no-run
      - name: Test
        run: cargo test --locked ${{ matrix.features }} --verbose
    env:
      # Warnings are ok for now here due to private APIs that will be public in the future.
      RUSTFLAGS: ""

  integration:
    name: "Integration tests"
    runs-on: ubuntu-24.04
    needs: modern-default
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: paketkoll_x86_64-unknown-linux-musl.tar.zst
      - name: Unpack binaries
        run: |
          tar xf ${GITHUB_WORKSPACE}/paketkoll.tar.zst
          mkdir -p target/debug
          mv paketkoll/* target/debug/
      - name: Install podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
          podman --version
      - name: Cache podman image
        id: cache-podman
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: |
            ~/podman_cache
          key: integration_tests-${{ runner.os }}-${{ hashFiles('integration_tests/images/arch/Containerfile') }}
      - name: Load cached image
        if: steps.cache-podman.outputs.cache-hit == 'true'
        run: |-
          set +ex
          podman load < ~/podman_cache/test_img.tar
      - name: Build & cache image
        if: steps.cache-podman.outputs.cache-hit != 'true'
        run: |-
          set +ex
          cd integration_tests/images/arch
          ./build_image.sh
          mkdir -p ~/podman_cache
          podman save localhost/test_img > ~/podman_cache/test_img.tar
      - name: Run integration tests
        run: |-
          cd integration_tests
          SKIP_BUILD_IMAGES=true ./run_tests.sh
