name: CI

permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lints:
    name: "Lint"
    uses: ./.github/workflows/act_lint.yml
    permissions:
      contents: read
      security-events: write

  build:
    name: "Build"
    uses: ./.github/workflows/act_build.yml

  mdbook:
    name: "Mdbook"
    uses: ./.github/workflows/act_mdbook.yml
