name: Release

permissions:
  attestations: write
  contents: write
  id-token: write

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:

  paketkoll:
    name: "Release paketkoll"
    if: github.repository_owner == 'VorpalBlade' && startsWith(github.event.release.name, 'paketkoll-v')
    uses: ./.github/workflows/act_build_release.yml
    with:
      release_name: ${{ github.event.release.name }}
      project: paketkoll
      archive_prefix: ${{ github.event.release.name }}
      binaries: paketkoll
    secrets:
      AUR_USERNAME: ${{ secrets.AUR_USERNAME }}
      AUR_EMAIL: ${{ secrets.AUR_EMAIL }}
      AUR_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}

  konfigkoll:
    name: "Release konfigkoll"
    if: github.repository_owner == 'VorpalBlade' && startsWith(github.event.release.name, 'konfigkoll-v')
    uses: ./.github/workflows/act_build_release.yml
    with:
      release_name: ${{ github.event.release.name }}
      project: konfigkoll
      archive_prefix: ${{ github.event.release.name }}
      binaries: konfigkoll,konfigkoll-rune
    secrets:
      AUR_USERNAME: ${{ secrets.AUR_USERNAME }}
      AUR_EMAIL: ${{ secrets.AUR_EMAIL }}
      AUR_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
